# Generated by Django 3.1.7 on 2021-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usereducation_userexperience_userprojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojects',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
