# Generated by Django 3.1.7 on 2021-03-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210316_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprojects',
            name='user',
        ),
    ]
