# Generated by Django 3.1.7 on 2021-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210316_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='description',
        ),
        migrations.AddField(
            model_name='usereducation',
            name='branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='course',
            field=models.CharField(max_length=255),
        ),
    ]
