# Generated by Django 3.1.7 on 2021-03-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210316_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprojects',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserExperience',
        ),
        migrations.DeleteModel(
            name='UserProjects',
        ),
    ]
