# Generated by Django 3.1.7 on 2021-03-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usereducation',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userexperience',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='userprojects',
            old_name='user',
            new_name='owner',
        ),
    ]
