# Generated by Django 3.1.7 on 2021-04-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0002_auto_20210317_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userexperience',
            options={'verbose_name_plural': 'Experience'},
        ),
    ]
