# Generated by Django 3.1.7 on 2021-04-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_auto_20210406_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprojects',
            options={'ordering': ['id'], 'verbose_name_plural': 'Projects'},
        ),
    ]
