# Generated by Django 3.1.7 on 2021-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0005_auto_20210407_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='branch',
            field=models.CharField(max_length=255),
        ),
    ]
